Ticket Booking/Controllers/CoachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ticket_Booking.Models;

namespace Ticket_Booking.Controllers
{
    public class CoachController : Controller
    {
        BinderModel binder = new BinderModel();
        // GET: /Coach/

        public ActionResult Index()
        {
            return View(binder.coach.ToList());
        }

        public ActionResult Create()
        {
            return View(new CoachModel());
        }

        [HttpPost]
        public ActionResult Save(CoachModel coach)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    binder.coach.Add(coach);
                    binder.SaveChanges();
                }
                catch (Exception e)
                {

                }

            }
            return RedirectToAction("Index"); ;
        }
        public ActionResult Delete(long id)
        {
            CoachModel ch = binder.coach.Find(id);
            binder.coach.Remove(ch);
            binder.SaveChanges();

            return RedirectToAction("Index");

        }

        public ActionResult Edit(long id)
        {
            CoachModel cm = binder.coach.Find(id);

            if (cm == null)
            {
                return HttpNotFound();
            }

            return View(cm);
        }

        [HttpPost]

        public ActionResult Edit(CoachModel chm)
        {
            if (ModelState.IsValid)
            {
                binder.Entry(chm).State = System.Data.Entity.EntityState.Modified;
                binder.SaveChanges();
            }

            return RedirectToAction("Index");
        }


    }
}

Ticket Booking/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ticket_Booking.Models;

namespace Ticket_Booking.Controllers
{
    public class LocationController : Controller
    {

        BinderModel binder = new BinderModel();
        //
        // GET: /Admin/

        public ActionResult Index()
        {
            return View(binder.location.ToList());
        }
        public ActionResult Create()
        {
            return View(new LocationModel());
        }

        [HttpPost]
        public ActionResult Save(LocationModel location)
        {
            if (ModelState.IsValid)
            {
                try {
                    binder.location.Add(location);
                    binder.SaveChanges();
                }
                catch (Exception e) { 

                }

            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            LocationModel lc = binder.location.Find(id);
            binder.location.Remove(lc);
            binder.SaveChanges();

            return RedirectToAction("Index");

        }

        public ActionResult Edit(long id)
        {
            LocationModel lm = binder.location.Find(id);
            if(lm ==null)
            {
                return HttpNotFound();
            }
            return View(lm);
        }
        [HttpPost]
        public ActionResult Edit(LocationModel lcm)
        {
            if (ModelState.IsValid)
            {
                binder.Entry(lcm).State = System.Data.Entity.EntityState.Modified;
                binder.SaveChanges();
            }
            return RedirectToAction("Index");
        }

    }
}

Ticket Booking/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Ticket_Booking.Models;

namespace Ticket_Booking.Controllers
{
    public class RegisterController : Controller
    {
        //
        // GET: /Register/
        BinderModel binder = new BinderModel();
        public ActionResult Index()
        {
            return View(new RegisterModel());
        }

        [HttpPost]
        public ActionResult Save(RegisterModel register)
        {
           /* if(string.IsNullOrEmpty(register.Name))
            {
                ModelState.AddModelError("Name", "Name is compulsory");
                return RedirectToAction("Index", "Home");
            }*/
            if (ModelState.IsValid)
            {
                try
                {
                   
                    binder.register.Add(register);
                    binder.SaveChanges();

                    TempData["Success"] = "Registration Done Successfully....";
                }
                catch (Exception e)
                {

                }
                 
            }
           return RedirectToAction("Index","Home");
        }

        //Login

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]

        public ActionResult Login(RegisterModel login)
        {
            var user = binder.register.Where(m=>m.UserName == login.UserName && m.Password == login.Password).FirstOrDefault();

            if (user != null)
            {
                Session["UserName"] = user.UserName.ToString();
                Session["Password"] = user.Password.ToString();
                global.logged = 1;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "username or password is wrong,");
            }

            return View();
        }


    }
}

Ticket Booking/Controllers/TripsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ticket_Booking.Models;

namespace Ticket_Booking.Controllers
{
    public class TripsController : Controller
    {
        BinderModel binder = new BinderModel();
        // GET: /Trips/

        public ActionResult Index()
        {          
            ViewBag.placeName = new SelectList(binder.location, "Id", "PlaceName");

            ViewBag.destination = new SelectList(binder.destination, "Id","Destination");

            ViewBag.coachType = new SelectList(binder.coach, "Id", "CoachType");

            return View(binder.trips.ToList());
        }
        public ActionResult Search(long RouteFrom, long RouteTo, long CoachType)
        {   
             
            return View(binder.trips.Where(m => m.RouteFrom == RouteFrom && m.RouteTo == RouteTo && m.CoachType == CoachType).ToList());
        }

        public ActionResult Create()
        {
            ViewBag.placeName = new SelectList(binder.location, "Id", "PlaceName");

            ViewBag.coachType= new SelectList(binder.coach, "Id", "CoachType");


            return View(new TripsModel());
        }

        [HttpPost]
        public ActionResult Save(TripsModel trips)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    binder.trips.Add(trips);
                    binder.SaveChanges();
                }
                catch (Exception e)
                {

                }

            }
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int id)
        {
            TripsModel trp = binder.trips.Find(id);
            binder.trips.Remove(trp);
            binder.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult Edit(int id)
        {
            TripsModel trp = binder.trips.Find(id);

            if (trp == null)
            {
                return HttpNotFound();
            }

            ViewBag.placeName = new SelectList(binder.location, "Id", "PlaceName");

            ViewBag.coachType = new SelectList(binder.coach, "Id", "CoachType");

            return View(trp);
        }

        [HttpPost]

        public ActionResult Edit(TripsModel trip)
        {
            if (ModelState.IsValid)
            {
                binder.Entry(trip).State = System.Data.Entity.EntityState.Modified;
                binder.SaveChanges();
            }

            return RedirectToAction("Index");
        }


    }
}

Ticket Booking/Views/Shared/_MasterLayout.cshtml
@{
    ViewBag.Title = "MasterLayout";
}
<!DOCTYPE html>

<style>
    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #4CAF50;
    }

    li {
        float: left;
        border-right: 1px solid #bbb;
    }

        li:last-child {
            border-right: none;
        }

        li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

            li a:hover:not(.active) {
                background-color: #0d7412;
            }

    .active {
        background-color: #4CAF50;
    }

    img {
        border-radius: 8px;
    }

    .buttonl {
        background-color: #4CAF50; /* Green */
        border: none;
        color: white;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin:25px;
        -webkit-transition-duration: 0.4s; /* Safari */
        transition-duration: 0.4s;
        cursor: pointer;
        border-radius:12px;
        width:130px;
        height:50px;
    }

    .button1 {
        background-color: #4CAF50;
        color: white;
        border: 2px solid #4CAF50;
    }

        .button1:hover {
            background-color: white;
            color:black;
        }

</style>

<html>
<head>
    <title>Ticket Booking</title>
    <!-- custom-theme -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
               function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //custom-theme -->
    <script type="text/javascript" src="/Content/jquery-1.11.1.min.js"></script>
    <script src='@Url.Content("~/Scripts/jquery-1.8.2.js")' type='text/javascript'></script>
    <script src='@Url.Content("~/Scripts/jquery.validate.js")' type='text/javascript'>         </script>
    <script src='@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")' type='text/javascript'></script>
    <link href=@Url.Content("/Content/style.css") rel="stylesheet" type="text/css" media="all" />
    <link href="//fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
</head>
<body class="bg agileinfo">
    <header>
        <div class="panel panel-default" style="">
            <div class="logoBox" style="float: left; margin: 5px; display: block;">
                <img src="/Content/Images/busLogo.png" onclick="" alt="Paris" width="600" height="80" />
            </div>
            <div class="loginBox" style="float:right;margin-right:25px;">
                
                @if (global.logged == 0) { 
                    
                     <button class="buttonl button1" onclick="loginClick()">log in</button>
                
                }
                else if (global.logged == 1)
                {
                    
                     <button class="buttonl button1" onclick="logout()" >log out</button>
                }
            </div>
        </div>
        <br />
        <br />
        <br />
        <br />
        <br/>
        <div class="panel-body">
            @if (global.logged == 1) { 
                
            <div class="navigation">
                <ul style="list-style-type: none; margin: 10px; padding: 2px; overflow: hidden;">
                    <li style=" float: left;"><a href="@Url.Action("Index","Home")" style="display: block; text-align: center; padding: 14px 16px; text-decoration: none;">Home</a></li>
                    <li style=" float: left;"><a href="@Url.Action("Index","Trips")" style="display: block; text-align: center; padding: 14px 16px; text-decoration: none;">Trips</a></li>
                    <li style=" float: left;"><a href="@Url.Action("Index","Location")" style="display: block;text-align: center;padding: 14px 16px; text-decoration: none;">Location</a></li>
                    <li style=" float: left;"><a href="@Url.Action("Index","Coach")" style="display: block;text-align: center; padding: 14px 16px;text-decoration: none;">Coach Type</a></li>
                </ul>
            </div>
                
            }

        </div>
    </header>

    <section>

        @RenderSection("bodypage", required: false)
        @RenderBody()

    </section>

    <div style="text-align: center; vertical-align: middle;">
        <br/>
        <br/>
        <p style="color: #dcffff">WE ACCEPT</p>

        <img src="https://s3.amazonaws.com/busbdimages/bank_logo.png" alt="" style="width:1100px;height:56px;">

    </div>

    <footer class=" footer">
        <h6 style="text-align: center; margin: 10px; background-color: #4CAF50; height: 25px; position:inherit">Copyright : Datagrid Limited</h6>
    </footer>

</body>
</html>

<script>

    function loginClick() {

          location.href = '@Url.Action("Login", "Register")';
    }
       
    function logout() {
           
          
          location.href = '@Url.Action("Index", "Home")';
        
    }         

</script>